spring:
  application:
    name: meet

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/meet_db
    username: meet
    password: meet

  jpa:
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true

  sql:
    init:
      mode: always

server:
  port: 8080

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

logging:
  level:
    root: INFO
    ru.aston.meet: DEBUG

springdoc:
  swagger-ui:
    path: /

kafka:
  config:
    bootstrap-servers: localhost:9092
    client-id-config: producer-1
    producer-key-serializer: org.apache.kafka.common.serialization.StringSerializer
    producer-value-serializer: ru.aston.meet.util.GeneralAvroSerializer
    meeting-topic: notifications.meets.v1
    invitation-topic: notifications.invitations.v1
    partipant-topic: notifications.partipants.v1